**난이도 하 (기초 전처리 — 분석 가능 형태 만들기)**

In [2]:
import pandas as pd

data = {
    "user_id": [101, 102, 103, 104, 105],
    "age": [23, None, 31, None, 28],
    "gender": ["F", "M", None, "F", "M"],
    "signup_date": ["2024-01-03", "2024-01-05", "2024-01-07", "2024-01-10", "2024-01-12"]
}

df = pd.DataFrame(data)

In [3]:
df

   user_id   age gender signup_date
0      101  23.0      F  2024-01-03
1      102   NaN      M  2024-01-05
2      103  31.0   None  2024-01-07
3      104   NaN      F  2024-01-10
4      105  28.0      M  2024-01-12

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   user_id      5 non-null      int64
 1   age          3 non-null      float64
 2   gender       4 non-null      object
 3   signup_date  5 non-null      object
dtypes: float64(1), int64(1), object(2)
memory usage: 292.0+ bytes

In [5]:
df2 = df.dropna(subset=['age'])
df2

   user_id   age gender signup_date
0      101  23.0      F  2024-01-03
2      103  31.0   None  2024-01-07
4      105  28.0      M  2024-01-12

In [8]:
df2['signup_date'] = pd.to_datetime(df['signup_date'])
df2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, 0 to 4
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   user_id      3 non-null      int64
 1   age          3 non-null      float64
 2   gender       2 non-null      object
 3   signup_date  3 non-null      datetime64[ns]
dtypes: datetime64[ns](1), float64(1), int64(1), object(1)
memory usage: 120.0+ bytes

C:\Users\j2h09\AppData\Local\Temp\ipykernel_9224\1565197167.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['signup_date'] = pd.to_datetime(df['signup_date'])

In [13]:
df2['age_group'] = (df2['age']//10*10)
df2['age_group'] = df2['age_group'].astype(int).astype(str) + "대"
age_analysis = df2.groupby('age_group')['user_id'].nunique()

age_analysis

C:\Users\j2h09\AppData\Local\Temp\ipykernel_9224\1703532517.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['age_group'] = (df2['age']//10*10)
C:\Users\j2h09\AppData\Local\Temp\ipykernel_9224\1703532517.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['age_group'] = df2['age_group'].astype(int).astype(str) + "대"

age_group
20대    2
30대    1
Name: user_id, dtype: int64

**난이도 중 (정제 + 파생변수 생성)**

In [15]:
data = {
    "order_id": [1, 2, 3, 4, 5, 6],
    "user_id": [101, 101, 102, 103, 103, 103],
    "price": [12000, 15000, None, 8000, 9000, None],
    "category": ["food", "food", "beauty", "food", None, "beauty"]
}

df = pd.DataFrame(data)

In [16]:
df

   order_id  user_id    price category
0         1      101  12000.0     food
1         2      101  15000.0     food
2         3      102      NaN   beauty
3         4      103   8000.0     food
4         5      103   9000.0     None
5         6      103      NaN   beauty

In [25]:
df['price'] = df['price'].fillna(df['price'].mean())

df

   order_id  user_id    price category
0         1      101  12000.0     food
1         2      101  15000.0     food
2         3      102  10500.0   beauty
3         4      103   8000.0     food
4         5      103   9000.0  unknown
5         6      103   8500.0   beauty

In [26]:
df['category'] = df['category'].fillna('unknown')

df

   order_id  user_id    price category
0         1      101  12000.0     food
1         2      101  15000.0     food
2         3      102  10500.0   beauty
3         4      103   8000.0     food
4         5      103   9000.0  unknown
5         6      103   8500.0   beauty

In [27]:
user_analysis = df.groupby('user_id')['price'].agg(['sum','mean'])
user_analysis.columns = ['총 구매금액','평균 구매금액']

user_analysis

          총 구매금액  평균 구매금액
user_id
101      27000.0  13500.0
102      10500.0  10500.0
103      25500.0   8500.0

**난이도 상 (실무형 전처리 — 분석용 테이블 완성)**

In [35]:
data = {
    "user_id": [1, 2, 3, 4, 5],
    "join_date": ["2023-12-01", "2024-01-15", "2024-01-20", "2024-02-05", "2024-02-20"],
    "last_login": ["2024-02-28", None, "2024-02-25", "2024-02-27", None],
    "total_payment": [120000, 0, 45000, 89000, 0]
}

df = pd.DataFrame(data)
df

   user_id   join_date  last_login  total_payment
0        1  2023-12-01  2024-02-28         120000
1        2  2024-01-15        None              0
2        3  2024-01-20  2024-02-25          45000
3        4  2024-02-05  2024-02-27          89000
4        5  2024-02-20        None              0

In [ ]:
df['join_date']=pd.to_datetime(df['join_date'])
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   user_id        5 non-null      int64
 1   join_date      5 non-null      datetime64[ns]
 2   last_login     3 non-null      object
 3   total_payment  5 non-null      int64
dtypes: datetime64[ns](1), int64(2), object(1)
memory usage: 292.0+ bytes

In [37]:
# 날짜 데이터를 파이썬이 이해할 수 있도록 바꿔주기
df['last_login'] = pd.to_datetime(df['last_login'])

# 활동 여부 만들기
df.loc[df['last_login'].isnull(),'활동여부']='Inactive'
df.loc[df['last_login'].notnull(),'활동여부']='Activate'
df

   user_id   join_date last_login  total_payment      활동여부
0        1  2023-12-01 2024-02-28         120000  Activate
1        2  2024-01-15        NaT              0  Inactive
2        3  2024-01-20 2024-02-25          45000  Activate
3        4  2024-02-05 2024-02-27          89000  Activate
4        5  2024-02-20        NaT              0  Inactive

In [41]:
# 결제여부 만들기
df.loc[df['total_payment'] > 0,'결제여부']='Yes'
df.loc[df['total_payment']== 0,'결제여부']='No'
df

   user_id   join_date last_login  total_payment      활동여부 결제여부
0        1  2023-12-01 2024-02-28         120000  Activate  Yes
1        2  2024-01-15        NaT              0  Inactive   No
2        3  2024-01-20 2024-02-25          45000  Activate  Yes
3        4  2024-02-05 2024-02-27          89000  Activate  Yes
4        5  2024-02-20        NaT              0  Inactive   No

In [42]:
# 최근 접속 일수 (로그인 안 한 사람은 0으로 표시)
today = pd.to_datetime('2026-01-21')

df['최근 접속 일수'] = (today - df['last_login']).dt.days
df['최근 접속 일수'] = df['최근 접속 일수'].fillna(0)
df

   user_id   join_date last_login  total_payment      활동여부 결제여부  최근 접속 일수
0        1  2023-12-01 2024-02-28         120000  Activate  Yes     693.0
1        2  2024-01-15        NaT              0  Inactive   No       0.0
2        3  2024-01-20 2024-02-25          45000  Activate  Yes     696.0
3        4  2024-02-05 2024-02-27          89000  Activate  Yes     694.0
4        5  2024-02-20        NaT              0  Inactive   No       0.0