# [문제] H&M 고객 데이터(customer_hm.csv) — 기본 전처리 & 인덱싱/슬라이싱
> **주의:** 아래 문제는 반드시 제공된 문법 안에서만 풀이하세요.
- 사용 가능: `read_csv`, `to_csv`, `Series`, `DataFrame`, `head`, `shape`, `info`, `describe`, `value_counts`
- 인덱싱/슬라이싱: `[]`, `[['col1','col2']]`, `.loc`, `.iloc`, 슬라이싱(끝 포함/제외), 불리언 필터, `&`, `|`
- 결측치: `isnull().sum()`

## 0) 환경 세팅
- 파일 경로: `customer_hm.csv`
- 열(예시): `customer_id`, `FN`, `Active`, `club_member_status`, `fashion_news_frequency`, `age`

In [74]:

import pandas as pd

df = pd.read_csv('customer_hm.csv')
print("로드 완료!")

로드 완료!

- customer_id : 고객 아이디 / 고객에게 고유 식별값 줌.
- FN : 패션뉴스 구독 여부
- Active : 고객 활성화 상태?
- club_member_status : 멤버십 가입 여부? / 연령대별 멤버십 가입 비율
- fasion_news_frequency : 뉴스 발송 빈도
- age : 고객 나이 / 연령대별 고객 수 (브랜드 이용하는 주 연령대)

### 문제 1. 데이터 처음 5행을 확인하세요 (`head()`).

In [75]:
df.head()
# cutomer_id는 최대한 안 건드는게 좋다.

,customer_id,FN,Active,club_member_status,fashion_news_frequency,age
0,00000dbacae5abe5e23885899a1fa44253a17956c6d1c3...,0,0,ACTIVE,NONE,49
1,0000423b00ade91418cceaf3b26c6af3dd342b51fd051e...,0,0,ACTIVE,NONE,25
2,000058a12d5b43e67d225668fa1f8d618c13dc232df0ca...,0,0,ACTIVE,NONE,24
3,00005ca1c9ed5f5146b52ac8639a40ca9d57aeff4d1bd2...,0,0,ACTIVE,NONE,54
4,00006413d8573cd20ed7128e53b7b13819fe5cfc2d801f...,1,1,ACTIVE,Regularly,52

### 문제 2. 데이터의 행, 열 개수를 확인하세요 (`shape`).

In [76]:
df.shape

(1048575, 6)

### 문제 3. 각 컬럼의 타입과 결측치를 포함한 요약 정보를 확인하세요 (`info()`).

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1048575 entries, 0 to 1048574
Data columns (total 6 columns):
 #   Column                  Non-Null Count    Dtype
---  ------                  --------------    -----
 0   customer_id             1048575 non-null  object
 1   FN                      1048575 non-null  int64
 2   Active                  1048575 non-null  int64
 3   club_member_status      1048575 non-null  object
 4   fashion_news_frequency  1048574 non-null  object
 5   age                     1048575 non-null  int64
dtypes: int64(3), object(3)
memory usage: 48.0+ MB

### 문제 4. 수치형 컬럼들의 통계 요약을 확인하세요 (`describe()`).

In [78]:
df.describe().round(2)
df.describe().T # 행과 열을 바꾸는 전치.

            count       mean        std   min   25%   50%   75%   max
FN      1048575.0   0.355540   0.478677   0.0   0.0   0.0   1.0   1.0
Active  1048575.0   0.346133   0.475736   0.0   0.0   0.0   1.0   1.0
age     1048575.0  36.369194  14.308991  16.0  24.0  32.0  49.0  99.0

### 문제 5. `customer_id`, `age`, `club_member_status` 열만 선택해 처음 5행을 출력하세요 (`[['col1','col2']]`).

In [79]:
df[['customer_id', 'age','club_member_status']].head()

                                         customer_id  age club_member_status
0  00000dbacae5abe5e23885899a1fa44253a17956c6d1c3...   49             ACTIVE
1  0000423b00ade91418cceaf3b26c6af3dd342b51fd051e...   25             ACTIVE
2  000058a12d5b43e67d225668fa1f8d618c13dc232df0ca...   24             ACTIVE
3  00005ca1c9ed5f5146b52ac8639a40ca9d57aeff4d1bd2...   54             ACTIVE
4  00006413d8573cd20ed7128e53b7b13819fe5cfc2d801f...   52             ACTIVE

### 문제 6. `age` 한 열만 선택했을 때와 두 중괄호로 선택했을 때의 차이를 확인하세요 (`Series vs DataFrame`).

In [80]:
df['age']

0          49
1          25
2          24
3          54
4          52
           ..
1048570    22
1048571    41
1048572    38
1048573    54
1048574    49
Name: age, Length: 1048575, dtype: int64

In [81]:
df[['age']]

         age
0         49
1         25
2         24
3         54
4         52
...      ...
1048570   22
1048571   41
1048572   38
1048573   54
1048574   49

[1048575 rows x 1 columns]

### 문제 7. `.loc`으로 0~5행(끝 포함)과 `['customer_id','club_member_status','age']` 열을 선택해 보세요.

In [82]:
df.loc[0:5, ['customer_id','club_member_status','age']]

                                         customer_id club_member_status  age
0  00000dbacae5abe5e23885899a1fa44253a17956c6d1c3...             ACTIVE   49
1  0000423b00ade91418cceaf3b26c6af3dd342b51fd051e...             ACTIVE   25
2  000058a12d5b43e67d225668fa1f8d618c13dc232df0ca...             ACTIVE   24
3  00005ca1c9ed5f5146b52ac8639a40ca9d57aeff4d1bd2...             ACTIVE   54
4  00006413d8573cd20ed7128e53b7b13819fe5cfc2d801f...             ACTIVE   52
5  0000757967448a6cb83efb3ea7a3fb9d418ac7adf2379d...             ACTIVE   20

In [83]:
df.loc[4:6, ['Active']]

   Active
4       1
5       0
6       1

### 문제 8. `.iloc`으로 0~6행(끝 제외)과 열 위치 `[0,1,2,5]`를 선택해 보세요.

In [84]:
df.iloc[0:7, [0,1,2,5]]

                                         customer_id  FN  Active  age
0  00000dbacae5abe5e23885899a1fa44253a17956c6d1c3...   0       0   49
1  0000423b00ade91418cceaf3b26c6af3dd342b51fd051e...   0       0   25
2  000058a12d5b43e67d225668fa1f8d618c13dc232df0ca...   0       0   24
3  00005ca1c9ed5f5146b52ac8639a40ca9d57aeff4d1bd2...   0       0   54
4  00006413d8573cd20ed7128e53b7b13819fe5cfc2d801f...   1       1   52
5  0000757967448a6cb83efb3ea7a3fb9d418ac7adf2379d...   0       0   20
6  00007d2de826758b65a93dd24ce629ed66842531df6699...   1       1   32

### 문제 9. 불리언 필터로 `age >= 50`인 행만 선택하고 `['customer_id','age','Active']` 열만 보세요.

In [85]:
mask = df['age'] >= 50
df.loc[mask, ['customer_id','age','Active']]

                                               customer_id  age  Active
3        00005ca1c9ed5f5146b52ac8639a40ca9d57aeff4d1bd2...   54       0
4        00006413d8573cd20ed7128e53b7b13819fe5cfc2d801f...   52       1
12       00009d946eec3ea54add5ba56d5210ea898def4b46c685...   56       1
14       0000b2f1829e23b24feec422ef13df3ccedaedc85368e6...   54       1
15       0000b7a134c3ec0d8842fad1fd4ca28517424c14fc4848...   75       0
...                                                    ...  ...     ...
1048555  c88ed14b441c956cad259d9ec588fa0e62a53f38c85f8b...   57       1
1048559  c88edd334619bcbb99a989a9897fb58f8048c5432edd35...   64       0
1048560  c88ee2bf9eff1dd1f88e0660e700c536e2d5d32662abd1...   52       0
1048561  c88ef06636e7b60623be92eff392af29d3271eed02fb57...   52       0
1048573  c88fa15c06519c4bdcab386fea313b226113584b729874...   54       1

[245566 rows x 3 columns]

### 문제 10. 복합 조건으로 `Active == 1` AND `fashion_news_frequency == 'Regularly'`인 행을 선택하고 `['customer_id','fashion_news_frequency','age']`만 보세요.

In [99]:
conditions = (df['Active'] == 1) & (df['fashion_news_frequency'] == 'Regularly')

df.loc[conditions, ['customer_id','fashion_news_frequency','age']]

,customer_id,fashion_news_frequency,age
4,00006413d8573cd20ed7128e53b7b13819fe5cfc2d801f...,Regularly,52
6,00007d2de826758b65a93dd24ce629ed66842531df6699...,Regularly,32
12,00009d946eec3ea54add5ba56d5210ea898def4b46c685...,Regularly,56
13,0000ae1bbb25e04bdc7e35f718e852adfb3fbb72ef38b3...,Regularly,29
14,0000b2f1829e23b24feec422ef13df3ccedaedc85368e6...,Regularly,54
...,...,...,...
1041124,c88f46be101e5795b5d346e861a6b9091b03d8fbb200d6...,Regularly,18
1041125,c88f47ef5f8ad8addaafcacff4c1b637efb2e6b81d4d74...,Regularly,20
1041126,c88f5971612e659a4e90d6f08d9c29bdf1e4268fcf52d5...,Regularly,22
1041127,c88f5d0deba322a686e7928da6a7f3d2318e102d1c2cdb...,Regularly,41
1041129,c88fa15c06519c4bdcab386fea313b226113584b729874...,Regularly,54

In [103]:
# culb_member_status가 Active 이거나 FN이 0이고 age가 35세 이상인 행

conditions = (df['club_member_status'] == 'Active') | (df['FN'] == 0) & (df['age'] >= 35)

result = df.loc[conditions, ['customer_id','fashion_news_frequency','age']]
result.head()
type(conditions)

pandas.core.series.Series

### 문제 11. 범주형 컬럼 `club_member_status`의 분포를 확인하세요 (`value_counts()`).

In [101]:
df['club_member_status'].value_counts()

club_member_status
ACTIVE        975263
PRE-CREATE     65517
LEFT CLUB        351
Name: count, dtype: int64

### 문제 12. 컬럼별 결측치 개수를 확인하세요 (`isnull().sum()`).

In [89]:
df.isnull().sum()

customer_id               0
FN                        0
Active                    0
club_member_status        0
fashion_news_frequency    1
age                       0
dtype: int64

### 문제 13. `age >= 18`인 행만 골라 `output/hm_adults.csv`로 저장하세요 (`to_csv`).

In [ ]:
hm_adults = df.loc[df['age'] >= 18]
hm_adults.to_csv('hm_adults.csv', index = False)

In [97]:
df = pd.read_csv('hm_adults.csv')
df.describe().round(2)

               FN      Active         age
count  1041131.00  1041131.00  1041131.00
mean         0.36        0.35       36.51
std          0.48        0.48       14.27
min          0.00        0.00       18.00
25%          0.00        0.00       24.00
50%          0.00        0.00       32.00
75%          1.00        1.00       49.00
max          1.00        1.00       99.00