# 서울시 부동산 2024 (2024.csv)

## 문제 0 - 데이터 로딩
데이터는 다음 경로에서 읽어옵니다: `2024.csv`  
encoding="cp949" 옵션 권장

In [3]:
# TODO: 여기에서 코드를 작성하세요.
import pandas as pd

df = pd.read_csv('2024.csv',encoding = "cp949")

C:\Users\j2h09\AppData\Local\Temp\ipykernel_4160\1259630763.py:4: DtypeWarning: Columns (7,8) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('2024.csv',encoding = "cp949")

In [4]:
len(df)

77523

### 문제 1 — 조건 필터링(AND)
- 자치구명이 '강남구' **이면서** 건물용도가 '오피스텔'인 행만 필터링하세요.

In [5]:
# TODO: 여기에서 코드를 작성하세요.
df_gangnam_of = (df['자치구명'] == "강남구") & (df['건물용도'] == "오피스텔")

df.loc[df_gangnam_of]

,접수연도,자치구코드,자치구명,법정동코드,법정동명,지번구분,지번구분명,본번,부번,건물명,...,물건금액(만원),건물면적(㎡),토지면적(㎡),층,권리구분,취소일,건축년도,건물용도,신고구분,신고한 개업공인중개사 시군구명
39,2024,11680,강남구,10500,삼성동,1.0,대지,141.0,10.0,삼성동 롯데캐슬 클라쎄,...,51000,29.373,43.2521,5.0,NaN,NaN,2019.0,오피스텔,중개거래,서울 강남구
80,2024,11680,강남구,10100,역삼동,1.0,대지,823.0,33.0,강남루덴스 오피스텔,...,39000,27.640,43.9800,5.0,NaN,NaN,2021.0,오피스텔,직거래,NaN
289,2024,11680,강남구,11200,자곡동,1.0,대지,655.0,0.0,강남 푸르지오시티 2차(PRUGIO CITYⅡ),...,15000,21.872,28.9680,4.0,NaN,NaN,2014.0,오피스텔,중개거래,서울 강남구
324,2024,11680,강남구,10100,역삼동,1.0,대지,719.0,24.0,역삼역센트럴푸르지오시티,...,57000,39.304,62.7200,7.0,NaN,NaN,2019.0,오피스텔,중개거래,서울 강남구
326,2024,11680,강남구,10100,역삼동,1.0,대지,822.0,7.0,목화밀라트,...,31500,31.330,48.1300,16.0,NaN,NaN,2004.0,오피스텔,중개거래,서울 강남구
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76930,2024,11680,강남구,10100,역삼동,1.0,대지,0605,0017,태건 강남 헤븐리치 더써밋 761,...,24400,14.770,23.1000,13.0,NaN,NaN,2021.0,오피스텔,중개거래,서울 강남구
77177,2024,11680,강남구,10100,역삼동,1.0,대지,0825,0024,강남역 효성해링턴 타워 더퍼스트,...,28200,25.730,34.0300,3.0,NaN,NaN,2014.0,오피스텔,중개거래,서울 강남구
77189,2024,11680,강남구,10400,청담동,1.0,대지,0130,0009,현대 오피스텔,...,27500,20.700,27.5000,5.0,NaN,NaN,1991.0,오피스텔,중개거래,서울 강남구
77297,2024,11680,강남구,10400,청담동,1.0,대지,0130,0009,현대 오피스텔,...,31000,25.200,33.4900,4.0,NaN,NaN,1991.0,오피스텔,중개거래,서울 강남구
77416,2024,11680,강남구,10800,논현동,1.0,대지,0152,0005,논현동대우아이빌 힐타운,...,32000,40.550,54.1800,6.0,NaN,NaN,2003.0,오피스텔,중개거래,서울 강남구

### 문제 2 — 조건 필터링(OR)
- 층이 10층 이상 **또는** 물건금액(만원)이 100000 이상인 행만 필터링하세요.

In [6]:
# TODO: 여기에서 코드를 작성하세요.
condition = (df['층'] >= 10) | (df['물건금액(만원)'] >= 100000)
df.loc[condition]

,접수연도,자치구코드,자치구명,법정동코드,법정동명,지번구분,지번구분명,본번,부번,건물명,...,물건금액(만원),건물면적(㎡),토지면적(㎡),층,권리구분,취소일,건축년도,건물용도,신고구분,신고한 개업공인중개사 시군구명
5,2024,11590,동작구,10900,신대방동,NaN,NaN,NaN,NaN,NaN,...,744000,1502.310,534.000,NaN,NaN,NaN,1987.0,단독다가구,직거래,NaN
6,2024,11200,성동구,10200,하왕십리동,1.0,대지,890.0,181.0,동인드림힐스,...,28850,27.510,44.522,11.0,NaN,NaN,2017.0,오피스텔,중개거래,서울 성동구
7,2024,11545,금천구,10300,시흥동,1.0,대지,882.0,61.0,와이즈플레이스,...,9300,14.220,0.000,17.0,NaN,NaN,2012.0,아파트,중개거래,서울 금천구
8,2024,11230,동대문구,10600,장안동,1.0,대지,580.0,0.0,장안위더스빌,...,76000,107.970,0.000,16.0,NaN,NaN,2011.0,아파트,직거래,NaN
13,2024,11410,서대문구,12000,남가좌동,1.0,대지,385.0,0.0,DMC파크뷰자이1단지,...,172000,120.492,0.000,25.0,NaN,NaN,2015.0,아파트,중개거래,서울 서대문구
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77510,2024,11440,마포구,11200,현석동,1.0,대지,0220,0000,밤섬힐스테이트,...,127500,59.400,0.000,24.0,NaN,20241007.0,1999.0,아파트,중개거래,서울 마포구
77514,2024,11470,양천구,10100,신정동,1.0,대지,1307,0000,경남아너스빌,...,121500,84.990,NaN,2.0,NaN,20240228.0,2004.0,아파트,중개거래,서울 강서구
77515,2024,11650,서초구,10700,반포동,1.0,대지,0018,0001,래미안퍼스티지,...,775000,198.040,0.000,22.0,NaN,20240125.0,2009.0,아파트,중개거래,서울 서초구
77521,2024,11440,마포구,11000,노고산동,NaN,NaN,NaN,NaN,NaN,...,195000,157.450,116.700,NaN,NaN,20240417.0,1988.0,단독다가구,NaN,NaN
77522,2024,11305,강북구,10100,미아동,NaN,NaN,NaN,NaN,NaN,...,164000,293.080,136.000,NaN,NaN,20240905.0,1994.0,단독다가구,NaN,NaN

### 문제 3 — 결측치 조건
- 취소일이 결측(`NaN`)인 행만 필터링하세요. (거래 취소가 없는 건)

In [7]:
# TODO: 여기에서 코드를 작성하세요.
condition = df['취소일'].isna()
df[condition]

,접수연도,자치구코드,자치구명,법정동코드,법정동명,지번구분,지번구분명,본번,부번,건물명,...,물건금액(만원),건물면적(㎡),토지면적(㎡),층,권리구분,취소일,건축년도,건물용도,신고구분,신고한 개업공인중개사 시군구명
0,2024,11380,은평구,10200,녹번동,1.0,대지,86.0,125.0,성원빌라(86-125),...,16400,53.07,25.0000,4.0,NaN,NaN,1991.0,연립다세대,중개거래,서울 은평구
1,2024,11500,강서구,10300,화곡동,1.0,대지,924.0,4.0,팔팔빌라,...,35000,39.24,27.0000,2.0,NaN,NaN,1986.0,연립다세대,직거래,NaN
2,2024,11560,영등포구,11100,당산동1가,1.0,대지,143.0,0.0,다솔시티하임,...,30000,29.54,14.0000,5.0,NaN,NaN,2017.0,연립다세대,직거래,NaN
3,2024,11560,영등포구,12800,양평동4가,1.0,대지,220.0,0.0,해울빌,...,36000,40.41,63.6400,3.0,NaN,NaN,2021.0,오피스텔,중개거래,서울 용산구
4,2024,11410,서대문구,11200,대현동,1.0,대지,90.0,77.0,유씨유 이대,...,19300,17.31,30.8725,5.0,NaN,NaN,2018.0,오피스텔,중개거래,서울 서대문구
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77503,2024,11740,강동구,10900,천호동,1.0,대지,0330,0024,경복빌라,...,28500,44.11,32.9900,1.0,NaN,NaN,1991.0,연립다세대,중개거래,서울 강동구
77504,2024,11215,광진구,10700,화양동,1.0,대지,0527,0000,KCC파크타운,...,19000,25.79,37.3600,14.0,NaN,NaN,2005.0,오피스텔,중개거래,서울 광진구
77505,2024,11440,마포구,12200,합정동,1.0,대지,0369,0010,그레이스빌2차A,...,26300,22.44,12.6500,5.0,NaN,NaN,2004.0,연립다세대,직거래,NaN
77506,2024,11440,마포구,12600,중동,1.0,대지,0039,0009,백명TRENDYAPT,...,76000,107.48,0.0000,6.0,NaN,NaN,2004.0,아파트,중개거래,서울 마포구
77507,2024,11200,성동구,10600,사근동,1.0,대지,0314,0000,벽산,...,59000,59.84,0.0000,1.0,NaN,NaN,2000.0,아파트,중개거래,서울 성동구

### 문제 4 — 특정 값 필터링
- 신고구분이 '직거래'인 행만 필터링하세요.

In [8]:
# TODO: 여기에서 코드를 작성하세요.
condition = df['신고구분'] == '직거래'
df.loc[condition]

,접수연도,자치구코드,자치구명,법정동코드,법정동명,지번구분,지번구분명,본번,부번,건물명,...,물건금액(만원),건물면적(㎡),토지면적(㎡),층,권리구분,취소일,건축년도,건물용도,신고구분,신고한 개업공인중개사 시군구명
1,2024,11500,강서구,10300,화곡동,1.0,대지,924.0,4.0,팔팔빌라,...,35000,39.24,27.00,2.0,NaN,NaN,1986.0,연립다세대,직거래,NaN
2,2024,11560,영등포구,11100,당산동1가,1.0,대지,143.0,0.0,다솔시티하임,...,30000,29.54,14.00,5.0,NaN,NaN,2017.0,연립다세대,직거래,NaN
5,2024,11590,동작구,10900,신대방동,NaN,NaN,NaN,NaN,NaN,...,744000,1502.31,534.00,NaN,NaN,NaN,1987.0,단독다가구,직거래,NaN
8,2024,11230,동대문구,10600,장안동,1.0,대지,580.0,0.0,장안위더스빌,...,76000,107.97,0.00,16.0,NaN,NaN,2011.0,아파트,직거래,NaN
41,2024,11530,구로구,11000,온수동,1.0,대지,23.0,0.0,아델리안,...,24600,35.40,21.00,2.0,NaN,NaN,2019.0,연립다세대,직거래,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77494,2024,11740,강동구,10900,천호동,1.0,대지,0423,0200,강동 밀레니얼 중흥S-클래스,...,96450,84.19,0.00,7.0,분양권,NaN,0.0,아파트,직거래,NaN
77495,2024,11620,관악구,10100,봉천동,1.0,대지,0635,0534,더블레스2차,...,26000,35.69,21.66,3.0,NaN,NaN,2017.0,연립다세대,직거래,NaN
77505,2024,11440,마포구,12200,합정동,1.0,대지,0369,0010,그레이스빌2차A,...,26300,22.44,12.65,5.0,NaN,NaN,2004.0,연립다세대,직거래,NaN
77511,2024,11320,도봉구,10600,방학동,1.0,대지,0522,0000,북한산팰리스아파트,...,50000,159.03,NaN,2.0,NaN,20240430.0,2001.0,아파트,직거래,NaN
77512,2024,11305,강북구,10300,수유동,1.0,대지,0441,0011,가온리치빌(씨동),...,23000,29.64,21.54,2.0,NaN,20240426.0,2023.0,연립다세대,직거래,NaN

### 문제 5 — 정렬
- 물건금액(만원) 기준 **내림차순** 정렬 후 상위 10행을 출력하세요.

In [9]:
# TODO: 여기에서 코드를 작성하세요.
df.sort_values(by="물건금액(만원)", ascending = False)

,접수연도,자치구코드,자치구명,법정동코드,법정동명,지번구분,지번구분명,본번,부번,건물명,...,물건금액(만원),건물면적(㎡),토지면적(㎡),층,권리구분,취소일,건축년도,건물용도,신고구분,신고한 개업공인중개사 시군구명
57768,2024,11680,강남구,10700,신사동,NaN,NaN,NaN,NaN,NaN,...,2850000,305.620,326.00,NaN,NaN,NaN,1982.0,단독다가구,중개거래,서울 서초구
20409,2024,11170,용산구,13100,한남동,1.0,대지,829.0,0.0,나인원한남,...,2200000,273.412,0.00,1.0,NaN,NaN,2019.0,아파트,직거래,NaN
39252,2024,11170,용산구,13100,한남동,1.0,대지,829.0,0.0,나인원한남,...,2000000,273.942,0.00,1.0,NaN,NaN,2019.0,아파트,중개거래,서울 용산구
54876,2024,11680,강남구,10700,신사동,NaN,NaN,NaN,NaN,NaN,...,1800000,599.650,226.00,NaN,NaN,20240726.0,1988.0,단독다가구,중개거래,서울 강남구
54856,2024,11680,강남구,10700,신사동,NaN,NaN,NaN,NaN,NaN,...,1800000,599.650,226.30,NaN,NaN,NaN,1988.0,단독다가구,중개거래,서울 강남구
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53081,2024,11290,성북구,13500,종암동,1.0,대지,28.0,264.0,리버가든빌,...,3800,8.480,5.00,4.0,NaN,NaN,2010.0,연립다세대,중개거래,서울 동대문구
13641,2024,11350,노원구,10300,공릉동,1.0,대지,269.0,11.0,(269-11),...,3800,14.700,9.00,-1.0,NaN,20240813.0,1987.0,연립다세대,직거래,NaN
22104,2024,11320,도봉구,10700,창동,1.0,대지,609.0,4.0,유성하이츠빌라,...,3500,27.220,12.00,-1.0,NaN,NaN,1993.0,연립다세대,직거래,NaN
43664,2024,11380,은평구,10700,응암동,1.0,대지,116.0,15.0,미성드림투유,...,3000,13.800,18.79,9.0,NaN,NaN,2002.0,오피스텔,중개거래,서울 은평구
2487,2024,11410,서대문구,11900,북가좌동,1.0,대지,5.0,123.0,비바췌빌,...,2600,26.160,9.00,-1.0,NaN,NaN,2001.0,연립다세대,직거래,NaN

### 문제 6 — 다중 정렬
- 건축년도 **오름차순**, 건물면적(㎡) **내림차순**으로 다중 정렬하세요.

In [10]:
# TODO: 여기에서 코드를 작성하세요.
df.sort_values(by=['건축년도', '건물면적(㎡)'], ascending = [True,False])

,접수연도,자치구코드,자치구명,법정동코드,법정동명,지번구분,지번구분명,본번,부번,건물명,...,물건금액(만원),건물면적(㎡),토지면적(㎡),층,권리구분,취소일,건축년도,건물용도,신고구분,신고한 개업공인중개사 시군구명
50354,2024,11680,강남구,10300,개포동,1.0,대지,660.0,1.0,디에이치 퍼스티어 아이파크,...,560000,171.997,0.00,7.0,입주권,NaN,0.0,아파트,중개거래,서울 강남구
55077,2024,11740,강동구,10600,둔촌동,1.0,대지,170.0,1.0,올림픽파크 포레온,...,379824,156.980,0.00,35.0,입주권,NaN,0.0,아파트,중개거래,서울 강동구
67647,2024,11680,강남구,10300,개포동,1.0,대지,0660,0001,디에이치 퍼스티어 아이파크,...,795000,156.960,0.00,35.0,입주권,NaN,0.0,아파트,중개거래,서울 강남구
67702,2024,11680,강남구,10300,개포동,1.0,대지,0660,0001,디에이치 퍼스티어 아이파크,...,795000,156.960,0.00,35.0,입주권,20240220.0,0.0,아파트,중개거래,서울 강남구
27209,2024,11680,강남구,10300,개포동,1.0,대지,660.0,1.0,디에이치 퍼스티어 아이파크,...,610000,156.939,0.00,3.0,입주권,NaN,0.0,아파트,중개거래,서울 강남구
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
52457,2024,11560,영등포구,10800,영등포동7가,1.0,대지,94.0,298.0,리첸스타 오피스텔,...,10000,15.120,22.55,10.0,NaN,NaN,NaN,오피스텔,직거래,NaN
77327,2024,11500,강서구,10300,화곡동,1.0,대지,0982,0006,에벤에셀,...,8000,15.080,21.01,3.0,NaN,NaN,NaN,오피스텔,직거래,NaN
77328,2024,11500,강서구,10300,화곡동,1.0,대지,0982,0006,에벤에셀,...,8000,15.080,21.01,3.0,NaN,NaN,NaN,오피스텔,직거래,NaN
77332,2024,11500,강서구,10300,화곡동,1.0,대지,0982,0006,에벤에셀,...,8000,15.080,21.01,2.0,NaN,NaN,NaN,오피스텔,직거래,NaN
77336,2024,11500,강서구,10300,화곡동,1.0,대지,0982,0006,에벤에셀,...,8000,15.080,21.01,2.0,NaN,NaN,NaN,오피스텔,직거래,NaN

### 문제 7 — 열 제거
- 분석에 불필요하다고 가정하고 `권리구분` 열을 제거한 새로운 DataFrame을 만들고 컬럼 목록을 출력하세요.

In [11]:
# TODO: 여기에서 코드를 작성하세요.
df_cleaned = df.drop(columns= "권리구분")
df_cleaned

,접수연도,자치구코드,자치구명,법정동코드,법정동명,지번구분,지번구분명,본번,부번,건물명,계약일,물건금액(만원),건물면적(㎡),토지면적(㎡),층,취소일,건축년도,건물용도,신고구분,신고한 개업공인중개사 시군구명
0,2024,11380,은평구,10200,녹번동,1.0,대지,86.0,125.0,성원빌라(86-125),20241014,16400,53.07,25.0000,4.0,NaN,1991.0,연립다세대,중개거래,서울 은평구
1,2024,11500,강서구,10300,화곡동,1.0,대지,924.0,4.0,팔팔빌라,20241014,35000,39.24,27.0000,2.0,NaN,1986.0,연립다세대,직거래,NaN
2,2024,11560,영등포구,11100,당산동1가,1.0,대지,143.0,0.0,다솔시티하임,20241014,30000,29.54,14.0000,5.0,NaN,2017.0,연립다세대,직거래,NaN
3,2024,11560,영등포구,12800,양평동4가,1.0,대지,220.0,0.0,해울빌,20241014,36000,40.41,63.6400,3.0,NaN,2021.0,오피스텔,중개거래,서울 용산구
4,2024,11410,서대문구,11200,대현동,1.0,대지,90.0,77.0,유씨유 이대,20241014,19300,17.31,30.8725,5.0,NaN,2018.0,오피스텔,중개거래,서울 서대문구
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77518,2024,11530,구로구,10700,개봉동,1.0,대지,0170,0033,금석연립(170-33),20220708,9190,53.61,124.0000,1.0,20240207.0,1981.0,연립다세대,중개거래,서울 강남구
77519,2024,11530,구로구,10700,개봉동,1.0,대지,0170,0033,금석연립(170-33),20220708,9190,53.61,124.0000,1.0,20240207.0,1981.0,연립다세대,중개거래,서울 강남구
77520,2024,11530,구로구,10700,개봉동,1.0,대지,0170,0033,금석연립(170-33),20220708,9740,53.61,124.0000,2.0,20240207.0,1981.0,연립다세대,중개거래,서울 강남구
77521,2024,11440,마포구,11000,노고산동,NaN,NaN,NaN,NaN,NaN,20210719,195000,157.45,116.7000,NaN,20240417.0,1988.0,단독다가구,NaN,NaN
77522,2024,11305,강북구,10100,미아동,NaN,NaN,NaN,NaN,NaN,20210208,164000,293.08,136.0000,NaN,20240905.0,1994.0,단독다가구,NaN,NaN

### 문제 8 — 열 이름 변경
- `물건금액(만원)`→`거래금액_만원`, `건물면적(㎡)`→`건물면적_m2`, `토지면적(㎡)`→`토지면적_m2`로 변경하세요.

In [12]:
# TODO: 여기에서 코드를 작성하세요.
df.rename(columns = {'물건금액(만원)' : '거래금액_만원', '건물면적(㎡)' : '건물면적_m2', '토지면적(㎡)' : '토지면적_m2'})

,접수연도,자치구코드,자치구명,법정동코드,법정동명,지번구분,지번구분명,본번,부번,건물명,...,거래금액_만원,건물면적_m2,토지면적_m2,층,권리구분,취소일,건축년도,건물용도,신고구분,신고한 개업공인중개사 시군구명
0,2024,11380,은평구,10200,녹번동,1.0,대지,86.0,125.0,성원빌라(86-125),...,16400,53.07,25.0000,4.0,NaN,NaN,1991.0,연립다세대,중개거래,서울 은평구
1,2024,11500,강서구,10300,화곡동,1.0,대지,924.0,4.0,팔팔빌라,...,35000,39.24,27.0000,2.0,NaN,NaN,1986.0,연립다세대,직거래,NaN
2,2024,11560,영등포구,11100,당산동1가,1.0,대지,143.0,0.0,다솔시티하임,...,30000,29.54,14.0000,5.0,NaN,NaN,2017.0,연립다세대,직거래,NaN
3,2024,11560,영등포구,12800,양평동4가,1.0,대지,220.0,0.0,해울빌,...,36000,40.41,63.6400,3.0,NaN,NaN,2021.0,오피스텔,중개거래,서울 용산구
4,2024,11410,서대문구,11200,대현동,1.0,대지,90.0,77.0,유씨유 이대,...,19300,17.31,30.8725,5.0,NaN,NaN,2018.0,오피스텔,중개거래,서울 서대문구
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77518,2024,11530,구로구,10700,개봉동,1.0,대지,0170,0033,금석연립(170-33),...,9190,53.61,124.0000,1.0,NaN,20240207.0,1981.0,연립다세대,중개거래,서울 강남구
77519,2024,11530,구로구,10700,개봉동,1.0,대지,0170,0033,금석연립(170-33),...,9190,53.61,124.0000,1.0,NaN,20240207.0,1981.0,연립다세대,중개거래,서울 강남구
77520,2024,11530,구로구,10700,개봉동,1.0,대지,0170,0033,금석연립(170-33),...,9740,53.61,124.0000,2.0,NaN,20240207.0,1981.0,연립다세대,중개거래,서울 강남구
77521,2024,11440,마포구,11000,노고산동,NaN,NaN,NaN,NaN,NaN,...,195000,157.45,116.7000,NaN,NaN,20240417.0,1988.0,단독다가구,NaN,NaN
77522,2024,11305,강북구,10100,미아동,NaN,NaN,NaN,NaN,NaN,...,164000,293.08,136.0000,NaN,NaN,20240905.0,1994.0,단독다가구,NaN,NaN

### 문제 9 — 결측치 개수
- 각 열의 결측치 개수를 한 번에 확인하세요.

In [13]:
# TODO: 여기에서 코드를 작성하세요.
df.isna().sum()

접수연도                    0
자치구코드                   0
자치구명                    1
법정동코드                   0
법정동명                    0
지번구분                 2558
지번구분명                2558
본번                   2559
부번                   2559
건물명                  2559
계약일                     0
물건금액(만원)                0
건물면적(㎡)                 0
토지면적(㎡)              5077
층                    2558
권리구분                76823
취소일                 74351
건축년도                  267
건물용도                    0
신고구분                    2
신고한 개업공인중개사 시군구명     8854
dtype: int64

### 문제 10 — 결측치 채우기(수치형)
- 건축년도 결측치를 건축년도 **중앙값**으로 채운 새 DataFrame을 만들고, 채운 후 해당 열의 결측치 개수를 출력하세요.

In [14]:
# TODO: 여기에서 코드를 작성하세요.
s = df['건축년도']
s.fillna(s.median())
s.isna().sum()

np.int64(267)

### 문제 10-2 — 결측치 채우기(수치형)
- 건축년도 결측치를 자치구명별로 건축년도 **중앙값**으로 채운 새 DataFrame을 만들고, 채운 후 해당 열의 결측치 개수를 출력하세요.

In [15]:
# TODO: 여기에서 코드를 작성하세요.
df_new = df.copy()

df_new['건축년도'] = df_new['건축년도'].fillna(
    df_new.groupby('자치구명')['건축년도'].median()
)

In [16]:
df

,접수연도,자치구코드,자치구명,법정동코드,법정동명,지번구분,지번구분명,본번,부번,건물명,...,물건금액(만원),건물면적(㎡),토지면적(㎡),층,권리구분,취소일,건축년도,건물용도,신고구분,신고한 개업공인중개사 시군구명
0,2024,11380,은평구,10200,녹번동,1.0,대지,86.0,125.0,성원빌라(86-125),...,16400,53.07,25.0000,4.0,NaN,NaN,1991.0,연립다세대,중개거래,서울 은평구
1,2024,11500,강서구,10300,화곡동,1.0,대지,924.0,4.0,팔팔빌라,...,35000,39.24,27.0000,2.0,NaN,NaN,1986.0,연립다세대,직거래,NaN
2,2024,11560,영등포구,11100,당산동1가,1.0,대지,143.0,0.0,다솔시티하임,...,30000,29.54,14.0000,5.0,NaN,NaN,2017.0,연립다세대,직거래,NaN
3,2024,11560,영등포구,12800,양평동4가,1.0,대지,220.0,0.0,해울빌,...,36000,40.41,63.6400,3.0,NaN,NaN,2021.0,오피스텔,중개거래,서울 용산구
4,2024,11410,서대문구,11200,대현동,1.0,대지,90.0,77.0,유씨유 이대,...,19300,17.31,30.8725,5.0,NaN,NaN,2018.0,오피스텔,중개거래,서울 서대문구
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77518,2024,11530,구로구,10700,개봉동,1.0,대지,0170,0033,금석연립(170-33),...,9190,53.61,124.0000,1.0,NaN,20240207.0,1981.0,연립다세대,중개거래,서울 강남구
77519,2024,11530,구로구,10700,개봉동,1.0,대지,0170,0033,금석연립(170-33),...,9190,53.61,124.0000,1.0,NaN,20240207.0,1981.0,연립다세대,중개거래,서울 강남구
77520,2024,11530,구로구,10700,개봉동,1.0,대지,0170,0033,금석연립(170-33),...,9740,53.61,124.0000,2.0,NaN,20240207.0,1981.0,연립다세대,중개거래,서울 강남구
77521,2024,11440,마포구,11000,노고산동,NaN,NaN,NaN,NaN,NaN,...,195000,157.45,116.7000,NaN,NaN,20240417.0,1988.0,단독다가구,NaN,NaN
77522,2024,11305,강북구,10100,미아동,NaN,NaN,NaN,NaN,NaN,...,164000,293.08,136.0000,NaN,NaN,20240905.0,1994.0,단독다가구,NaN,NaN

### 문제 11 — 결측치 채우기(문자열)
- 건물명 결측치를 '미기재'로 채우고, 채운 후 해당 열의 결측치 개수를 출력하세요.

In [17]:
# TODO: 여기에서 코드를 작성하세요.

### 문제 12 — 중복 확인 및 제거(subset)
- 중복 기준을 `['자치구명','법정동명','계약일','건물면적(㎡)','물건금액(만원)']`으로 하여 중복 개수를 확인하고, 이를 기준으로 중복을 제거한 뒤 제거 전/후 행 수를 비교하세요.

In [18]:
# TODO: 여기에서 코드를 작성하세요.