In [1]:
import pandas as pd
import numpy as np

In [2]:
raw = [
    {"order_id":"O001","date":"2026-01-01 09:12","store":"광교점","menu":"Americano","price":"4,500원","qty":"2","paid":"TRUE","channel":"kiosk"},
    {"order_id":"O002","date":"2026/01/01 10:05","store":"광교점","menu":" Latte ","price":"5000","qty":1,"paid":"True","channel":"app"},
    {"order_id":"O003","date":"2026-01-02 12:20","store":"광교점","menu":"Mocha","price":None,"qty":2,"paid":"FALSE","channel":"kiosk"},
    {"order_id":"O004","date":"2026-01-03 15:40","store":"수원점","menu":"Americano","price":"4500","qty":None,"paid":True,"channel":"app"},
    {"order_id":"O005","date":"2026-01-03 18:10","store":"수원점","menu":"latte","price":"5,000원","qty":"3","paid":"TRUE","channel":"kiosk"},
    {"order_id":"O006","date":"2026-01-04 08:55","store":"수원점","menu":"Vanilla Latte","price":"5800원","qty":"1","paid":"TRUE","channel":"app"},
    {"order_id":"O007","date":"2026-01-04 09:10","store":"광교점","menu":"Mocha","price":"5500","qty":"1","paid":"FALSE","channel":"kiosk"},
    {"order_id":"O008","date":"2026-01-05 11:00","store":"광교점","menu":"Americano","price":"4500원","qty":"1","paid":"TRUE","channel":"app"},
]

df = pd.DataFrame(raw)
df.head()

  order_id              date store       menu   price   qty   paid channel
0     O001  2026-01-01 09:12   광교점  Americano  4,500원     2   TRUE   kiosk
1     O002  2026/01/01 10:05   광교점     Latte     5000     1   True     app
2     O003  2026-01-02 12:20   광교점      Mocha    None     2  FALSE   kiosk
3     O004  2026-01-03 15:40   수원점  Americano    4500  None   True     app
4     O005  2026-01-03 18:10   수원점      latte  5,000원     3   TRUE   kiosk

In [3]:
df.describe()

       order_id              date store       menu   price qty  paid channel
count         8                 8     8          8       7   7     8       8
unique        8                 8     2          5       7   5     4       2
top        O001  2026-01-01 09:12   광교점  Americano  4,500원   1  TRUE   kiosk
freq          1                 1     5          3       1   3     4       4

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   order_id  8 non-null      object
 1   date      8 non-null      object
 2   store     8 non-null      object
 3   menu      8 non-null      object
 4   price     7 non-null      object
 5   qty       7 non-null      object
 6   paid      8 non-null      object
 7   channel   8 non-null      object
dtypes: object(8)
memory usage: 644.0+ bytes

In [7]:
df["date"] = pd.to_datetime(df["date"], errors="coerce")
df["year"] = df["date"].dt.year
df["month"] = df["date"].dt.month
df["day_name"] = df["date"].dt.day_name()  # 요일(영문)
df["ym"] = df["date"].dt.to_period("M").astype(str)  # "2026-01" 형태

df

,order_id,date,store,menu,price,qty,paid,channel,year,month,day_name,ym
0,O001,2026-01-01 09:12:00,광교점,Americano,"4,500원",2,TRUE,kiosk,2026.0,1.0,Thursday,2026-01
1,O002,NaT,광교점,Latte,5000,1,True,app,NaN,NaN,NaN,NaT
2,O003,2026-01-02 12:20:00,광교점,Mocha,None,2,FALSE,kiosk,2026.0,1.0,Friday,2026-01
3,O004,2026-01-03 15:40:00,수원점,Americano,4500,None,True,app,2026.0,1.0,Saturday,2026-01
4,O005,2026-01-03 18:10:00,수원점,latte,"5,000원",3,TRUE,kiosk,2026.0,1.0,Saturday,2026-01
5,O006,2026-01-04 08:55:00,수원점,Vanilla Latte,5800원,1,TRUE,app,2026.0,1.0,Sunday,2026-01
6,O007,2026-01-04 09:10:00,광교점,Mocha,5500,1,FALSE,kiosk,2026.0,1.0,Sunday,2026-01
7,O008,2026-01-05 11:00:00,광교점,Americano,4500원,1,TRUE,app,2026.0,1.0,Monday,2026-01

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 12 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   order_id  8 non-null      object
 1   date      7 non-null      datetime64[ns]
 2   store     8 non-null      object
 3   menu      8 non-null      object
 4   price     7 non-null      object
 5   qty       7 non-null      object
 6   paid      8 non-null      object
 7   channel   8 non-null      object
 8   year      7 non-null      float64
 9   month     7 non-null      float64
 10  day_name  7 non-null      object
 11  ym        8 non-null      object
dtypes: datetime64[ns](1), float64(2), object(9)
memory usage: 900.0+ bytes

In [9]:
df.describe()

                                date    year  month
count                              7     7.0    7.0
mean   2026-01-03 15:29:34.285714176  2026.0    1.0
min              2026-01-01 09:12:00  2026.0    1.0
25%              2026-01-03 02:00:00  2026.0    1.0
50%              2026-01-03 18:10:00  2026.0    1.0
75%              2026-01-04 09:02:30  2026.0    1.0
max              2026-01-05 11:00:00  2026.0    1.0
std                              NaN     0.0    0.0

In [10]:
df["menu"] = df["menu"].astype(str).str.strip().str.title()
df

,order_id,date,store,menu,price,qty,paid,channel,year,month,day_name,ym
0,O001,2026-01-01 09:12:00,광교점,Americano,"4,500원",2,TRUE,kiosk,2026.0,1.0,Thursday,2026-01
1,O002,NaT,광교점,Latte,5000,1,True,app,NaN,NaN,NaN,NaT
2,O003,2026-01-02 12:20:00,광교점,Mocha,None,2,FALSE,kiosk,2026.0,1.0,Friday,2026-01
3,O004,2026-01-03 15:40:00,수원점,Americano,4500,None,True,app,2026.0,1.0,Saturday,2026-01
4,O005,2026-01-03 18:10:00,수원점,Latte,"5,000원",3,TRUE,kiosk,2026.0,1.0,Saturday,2026-01
5,O006,2026-01-04 08:55:00,수원점,Vanilla Latte,5800원,1,TRUE,app,2026.0,1.0,Sunday,2026-01
6,O007,2026-01-04 09:10:00,광교점,Mocha,5500,1,FALSE,kiosk,2026.0,1.0,Sunday,2026-01
7,O008,2026-01-05 11:00:00,광교점,Americano,4500원,1,TRUE,app,2026.0,1.0,Monday,2026-01

In [11]:
df["price"] = (
    df["price"]
    .astype(str)
    .str.replace(",", "", regex=False)
    .str.replace("원", "", regex=False)
)
df["price"] = pd.to_numeric(df["price"], errors="coerce")

df

,order_id,date,store,menu,price,qty,paid,channel,year,month,day_name,ym
0,O001,2026-01-01 09:12:00,광교점,Americano,4500.0,2,TRUE,kiosk,2026.0,1.0,Thursday,2026-01
1,O002,NaT,광교점,Latte,5000.0,1,True,app,NaN,NaN,NaN,NaT
2,O003,2026-01-02 12:20:00,광교점,Mocha,NaN,2,FALSE,kiosk,2026.0,1.0,Friday,2026-01
3,O004,2026-01-03 15:40:00,수원점,Americano,4500.0,None,True,app,2026.0,1.0,Saturday,2026-01
4,O005,2026-01-03 18:10:00,수원점,Latte,5000.0,3,TRUE,kiosk,2026.0,1.0,Saturday,2026-01
5,O006,2026-01-04 08:55:00,수원점,Vanilla Latte,5800.0,1,TRUE,app,2026.0,1.0,Sunday,2026-01
6,O007,2026-01-04 09:10:00,광교점,Mocha,5500.0,1,FALSE,kiosk,2026.0,1.0,Sunday,2026-01
7,O008,2026-01-05 11:00:00,광교점,Americano,4500.0,1,TRUE,app,2026.0,1.0,Monday,2026-01

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 12 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   order_id  8 non-null      object
 1   date      7 non-null      datetime64[ns]
 2   store     8 non-null      object
 3   menu      8 non-null      object
 4   price     7 non-null      float64
 5   qty       7 non-null      object
 6   paid      8 non-null      object
 7   channel   8 non-null      object
 8   year      7 non-null      float64
 9   month     7 non-null      float64
 10  day_name  7 non-null      object
 11  ym        8 non-null      object
dtypes: datetime64[ns](1), float64(3), object(8)
memory usage: 900.0+ bytes

In [13]:
df.describe()

                                date        price    year  month
count                              7     7.000000     7.0    7.0
mean   2026-01-03 15:29:34.285714176  4971.428571  2026.0    1.0
min              2026-01-01 09:12:00  4500.000000  2026.0    1.0
25%              2026-01-03 02:00:00  4500.000000  2026.0    1.0
50%              2026-01-03 18:10:00  5000.000000  2026.0    1.0
75%              2026-01-04 09:02:30  5250.000000  2026.0    1.0
max              2026-01-05 11:00:00  5800.000000  2026.0    1.0
std                              NaN   521.901286     0.0    0.0

In [14]:
df["qty"] = pd.to_numeric(df["qty"], errors="coerce")
df["qty"] = df["qty"].fillna(1)  # 실무에서 1로 대체하는 간단 예시(전략 설명)
df["qty"] = df["qty"].astype(int)

df

,order_id,date,store,menu,price,qty,paid,channel,year,month,day_name,ym
0,O001,2026-01-01 09:12:00,광교점,Americano,4500.0,2,TRUE,kiosk,2026.0,1.0,Thursday,2026-01
1,O002,NaT,광교점,Latte,5000.0,1,True,app,NaN,NaN,NaN,NaT
2,O003,2026-01-02 12:20:00,광교점,Mocha,NaN,2,FALSE,kiosk,2026.0,1.0,Friday,2026-01
3,O004,2026-01-03 15:40:00,수원점,Americano,4500.0,1,True,app,2026.0,1.0,Saturday,2026-01
4,O005,2026-01-03 18:10:00,수원점,Latte,5000.0,3,TRUE,kiosk,2026.0,1.0,Saturday,2026-01
5,O006,2026-01-04 08:55:00,수원점,Vanilla Latte,5800.0,1,TRUE,app,2026.0,1.0,Sunday,2026-01
6,O007,2026-01-04 09:10:00,광교점,Mocha,5500.0,1,FALSE,kiosk,2026.0,1.0,Sunday,2026-01
7,O008,2026-01-05 11:00:00,광교점,Americano,4500.0,1,TRUE,app,2026.0,1.0,Monday,2026-01

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 12 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   order_id  8 non-null      object
 1   date      7 non-null      datetime64[ns]
 2   store     8 non-null      object
 3   menu      8 non-null      object
 4   price     7 non-null      float64
 5   qty       8 non-null      int64
 6   paid      8 non-null      object
 7   channel   8 non-null      object
 8   year      7 non-null      float64
 9   month     7 non-null      float64
 10  day_name  7 non-null      object
 11  ym        8 non-null      object
dtypes: datetime64[ns](1), float64(3), int64(1), object(7)
memory usage: 900.0+ bytes

In [17]:
def to_bool(x):
    if isinstance(x, bool):
        return x
    x = str(x).strip().lower()
    return x in ["true", "1", "yes", "y"]

df["paid"] = df["paid"].apply(to_bool)
df

,order_id,date,store,menu,price,qty,paid,channel,year,month,day_name,ym
0,O001,2026-01-01 09:12:00,광교점,Americano,4500.0,2,True,kiosk,2026.0,1.0,Thursday,2026-01
1,O002,NaT,광교점,Latte,5000.0,1,True,app,NaN,NaN,NaN,NaT
2,O003,2026-01-02 12:20:00,광교점,Mocha,NaN,2,False,kiosk,2026.0,1.0,Friday,2026-01
3,O004,2026-01-03 15:40:00,수원점,Americano,4500.0,1,True,app,2026.0,1.0,Saturday,2026-01
4,O005,2026-01-03 18:10:00,수원점,Latte,5000.0,3,True,kiosk,2026.0,1.0,Saturday,2026-01
5,O006,2026-01-04 08:55:00,수원점,Vanilla Latte,5800.0,1,True,app,2026.0,1.0,Sunday,2026-01
6,O007,2026-01-04 09:10:00,광교점,Mocha,5500.0,1,False,kiosk,2026.0,1.0,Sunday,2026-01
7,O008,2026-01-05 11:00:00,광교점,Americano,4500.0,1,True,app,2026.0,1.0,Monday,2026-01

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 12 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   order_id  8 non-null      object
 1   date      7 non-null      datetime64[ns]
 2   store     8 non-null      object
 3   menu      8 non-null      object
 4   price     7 non-null      float64
 5   qty       8 non-null      int64
 6   paid      8 non-null      bool
 7   channel   8 non-null      object
 8   year      7 non-null      float64
 9   month     7 non-null      float64
 10  day_name  7 non-null      object
 11  ym        8 non-null      object
dtypes: bool(1), datetime64[ns](1), float64(3), int64(1), object(6)
memory usage: 844.0+ bytes

In [20]:
df["sales"] = np.where(df["paid"], df["price"] * df["qty"], 0)    #np.where(조건, 참일때값, 거짓일때값)
df[["order_id","date","store","menu","price","qty","paid","sales"]].head()

  order_id                date store       menu   price  qty   paid    sales
0     O001 2026-01-01 09:12:00   광교점  Americano  4500.0    2   True   9000.0
1     O002                 NaT   광교점      Latte  5000.0    1   True   5000.0
2     O003 2026-01-02 12:20:00   광교점      Mocha     NaN    2  False      0.0
3     O004 2026-01-03 15:40:00   수원점  Americano  4500.0    1   True   4500.0
4     O005 2026-01-03 18:10:00   수원점      Latte  5000.0    3   True  15000.0

In [21]:
store_summary = df.groupby("store").agg(
    total_sales=("sales","sum"),
    orders=("order_id","count"),
    paid_rate=("paid","mean")
).reset_index()

store_summary

  store  total_sales  orders  paid_rate
0   광교점      18500.0       5        0.6
1   수원점      25300.0       3        1.0

In [22]:
ym_day = df.groupby(["ym","day_name"]).agg(
    total_sales=("sales","sum"),
    orders=("order_id","count"),
    paid_rate=("paid","mean")
)

ym_day

                  total_sales  orders  paid_rate
ym      day_name
2026-01 Friday            0.0       1        0.0
        Monday         4500.0       1        1.0
        Saturday      19500.0       2        1.0
        Sunday         5800.0       2        0.5
        Thursday       9000.0       1        1.0

In [23]:
ym_day = ym_day.reset_index()
ym_day

        ym  day_name  total_sales  orders  paid_rate
0  2026-01    Friday          0.0       1        0.0
1  2026-01    Monday       4500.0       1        1.0
2  2026-01  Saturday      19500.0       2        1.0
3  2026-01    Sunday       5800.0       2        0.5
4  2026-01  Thursday       9000.0       1        1.0

In [24]:
pivot_sales = ym_day.pivot(index="ym", columns="day_name", values="total_sales").fillna(0) 
pivot_sales

day_name  Friday  Monday  Saturday  Sunday  Thursday
ym
2026-01      0.0  4500.0   19500.0  5800.0    9000.0

In [25]:
menu_map = pd.DataFrame([
    {"menu":"Americano", "category":"Coffee"},
    {"menu":"Latte", "category":"Coffee"},
    {"menu":"Mocha", "category":"Coffee"},
    {"menu":"Vanilla Latte", "category":"Latte Variations"},
])

menu_map

            menu          category
0      Americano            Coffee
1          Latte            Coffee
2          Mocha            Coffee
3  Vanilla Latte  Latte Variations

In [26]:
df2 = df.merge(menu_map, on="menu", how="left")
df2[["menu","category"]].drop_duplicates()

            menu          category
0      Americano            Coffee
1          Latte            Coffee
2          Mocha            Coffee
5  Vanilla Latte  Latte Variations

In [27]:
df2

,order_id,date,store,menu,price,qty,paid,channel,year,month,day_name,ym,sales,category
0,O001,2026-01-01 09:12:00,광교점,Americano,4500.0,2,True,kiosk,2026.0,1.0,Thursday,2026-01,9000.0,Coffee
1,O002,NaT,광교점,Latte,5000.0,1,True,app,NaN,NaN,NaN,NaT,5000.0,Coffee
2,O003,2026-01-02 12:20:00,광교점,Mocha,NaN,2,False,kiosk,2026.0,1.0,Friday,2026-01,0.0,Coffee
3,O004,2026-01-03 15:40:00,수원점,Americano,4500.0,1,True,app,2026.0,1.0,Saturday,2026-01,4500.0,Coffee
4,O005,2026-01-03 18:10:00,수원점,Latte,5000.0,3,True,kiosk,2026.0,1.0,Saturday,2026-01,15000.0,Coffee
5,O006,2026-01-04 08:55:00,수원점,Vanilla Latte,5800.0,1,True,app,2026.0,1.0,Sunday,2026-01,5800.0,Latte Variations
6,O007,2026-01-04 09:10:00,광교점,Mocha,5500.0,1,False,kiosk,2026.0,1.0,Sunday,2026-01,0.0,Coffee
7,O008,2026-01-05 11:00:00,광교점,Americano,4500.0,1,True,app,2026.0,1.0,Monday,2026-01,4500.0,Coffee

In [28]:
channel_map = {"kiosk":"키오스크", "app":"앱"}
df2["channel_kr"] = df2["channel"].map(channel_map).fillna("기타")
df2[["channel","channel_kr"]].drop_duplicates()

  channel channel_kr
0   kiosk       키오스크
1     app          앱

In [29]:
df2

,order_id,date,store,menu,price,qty,paid,channel,year,month,day_name,ym,sales,category,channel_kr
0,O001,2026-01-01 09:12:00,광교점,Americano,4500.0,2,True,kiosk,2026.0,1.0,Thursday,2026-01,9000.0,Coffee,키오스크
1,O002,NaT,광교점,Latte,5000.0,1,True,app,NaN,NaN,NaN,NaT,5000.0,Coffee,앱
2,O003,2026-01-02 12:20:00,광교점,Mocha,NaN,2,False,kiosk,2026.0,1.0,Friday,2026-01,0.0,Coffee,키오스크
3,O004,2026-01-03 15:40:00,수원점,Americano,4500.0,1,True,app,2026.0,1.0,Saturday,2026-01,4500.0,Coffee,앱
4,O005,2026-01-03 18:10:00,수원점,Latte,5000.0,3,True,kiosk,2026.0,1.0,Saturday,2026-01,15000.0,Coffee,키오스크
5,O006,2026-01-04 08:55:00,수원점,Vanilla Latte,5800.0,1,True,app,2026.0,1.0,Sunday,2026-01,5800.0,Latte Variations,앱
6,O007,2026-01-04 09:10:00,광교점,Mocha,5500.0,1,False,kiosk,2026.0,1.0,Sunday,2026-01,0.0,Coffee,키오스크
7,O008,2026-01-05 11:00:00,광교점,Americano,4500.0,1,True,app,2026.0,1.0,Monday,2026-01,4500.0,Coffee,앱

In [30]:
def sales_grade(row):
    if row["sales"] >= 10000:
        return "A"
    elif row["sales"] > 0:
        return "B"
    else:
        return "C"

df2["grade"] = df2.apply(sales_grade, axis=1)
df2[["order_id","sales","grade"]]

  order_id    sales grade
0     O001   9000.0     B
1     O002   5000.0     B
2     O003      0.0     C
3     O004   4500.0     B
4     O005  15000.0     A
5     O006   5800.0     B
6     O007      0.0     C
7     O008   4500.0     B

In [31]:
summary_A = df.groupby(["ym","day_name"]).agg(
    total_sales=("sales","sum"),
    paid_rate=("paid","mean")
).reset_index()

summary_A_pivot = summary_A.pivot(index="ym", columns="day_name", values="total_sales").fillna(0)

summary_A_pivot

day_name  Friday  Monday  Saturday  Sunday  Thursday
ym
2026-01      0.0  4500.0   19500.0  5800.0    9000.0

In [32]:
menu_summary = df2.groupby(["category","menu"]).agg(
    total_sales=("sales","sum"),
    total_qty=("qty","sum"),
    orders=("order_id","count"),
    paid_rate=("paid","mean")
).reset_index()

menu_summary = menu_summary.sort_values("total_sales", ascending=False)
menu_summary

           category           menu  total_sales  total_qty  orders  paid_rate
1            Coffee          Latte      20000.0          4       2        1.0
0            Coffee      Americano      18000.0          4       3        1.0
3  Latte Variations  Vanilla Latte       5800.0          1       1        1.0
2            Coffee          Mocha          0.0          3       2        0.0

In [33]:
menu_summary = menu_summary.sort_values(by=["category", "menu", "total_sales"],
                                        ascending=[True, True, True]).reset_index(drop=True)

menu_summary

           category           menu  total_sales  total_qty  orders  paid_rate
0            Coffee      Americano      18000.0          4       3        1.0
1            Coffee          Latte      20000.0          4       2        1.0
2            Coffee          Mocha          0.0          3       2        0.0
3  Latte Variations  Vanilla Latte       5800.0          1       1        1.0

In [34]:
import os
os.makedirs("data", exist_ok=True)

summary_A.to_csv("data/summary_A_long.csv", index=False)
summary_A_pivot.to_csv("data/summary_A_pivot.csv")
menu_summary.to_csv("data/summary_B_menu.csv", index=False)

In [35]:
check = pd.read_csv("data/summary_B_menu.csv")
check.head()

           category           menu  total_sales  total_qty  orders  paid_rate
0            Coffee      Americano      18000.0          4       3        1.0
1            Coffee          Latte      20000.0          4       2        1.0
2            Coffee          Mocha          0.0          3       2        0.0
3  Latte Variations  Vanilla Latte       5800.0          1       1        1.0