# H&M 고객 데이터 (customer_hm.csv)


## 문제 0 - 데이터 로딩
데이터는 다음 경로에서 읽어옵니다: `customer_hm.csv`

In [1]:
# TODO: 여기에서 코드를 작성하세요.
import pandas as pd

df = pd.read_csv('customer_hm.csv')
df.head()

,customer_id,FN,Active,club_member_status,fashion_news_frequency,age
0,00000dbacae5abe5e23885899a1fa44253a17956c6d1c3...,0,0,ACTIVE,NONE,49
1,0000423b00ade91418cceaf3b26c6af3dd342b51fd051e...,0,0,ACTIVE,NONE,25
2,000058a12d5b43e67d225668fa1f8d618c13dc232df0ca...,0,0,ACTIVE,NONE,24
3,00005ca1c9ed5f5146b52ac8639a40ca9d57aeff4d1bd2...,0,0,ACTIVE,NONE,54
4,00006413d8573cd20ed7128e53b7b13819fe5cfc2d801f...,1,1,ACTIVE,Regularly,52

### 문제 1 — 조건 필터링
- 나이가 40세 이상인 고객 행만 필터링하여 첫 5행을 출력하고, 행 개수를 함께 출력하세요.

In [7]:
# TODO: 여기에서 코드를 작성하세요.
mask = df.loc[df['age'] >= 40]
print(mask.head())
len(mask.head())

                                          customer_id  FN  Active  \
0   00000dbacae5abe5e23885899a1fa44253a17956c6d1c3...   0       0
3   00005ca1c9ed5f5146b52ac8639a40ca9d57aeff4d1bd2...   0       0
4   00006413d8573cd20ed7128e53b7b13819fe5cfc2d801f...   1       1
11  00009c2aeae8761f738e4f937d9be6b49861a66339c2b1...   0       0
12  00009d946eec3ea54add5ba56d5210ea898def4b46c685...   1       1

   club_member_status fashion_news_frequency  age
0              ACTIVE                   NONE   49
3              ACTIVE                   NONE   54
4              ACTIVE              Regularly   52
11             ACTIVE                   NONE   49
12             ACTIVE              Regularly   56

5

### 문제 2 — 다중 조건
- 클럽 회원 상태가 'ACTIVE' 이면서 `FN` 값이 1인 고객만 필터링하세요.

In [ ]:
# TODO: 여기에서 코드를 작성하세요.
conditions = (df['club_member_status'] == 'ACTIVE') & (df['FN'] == 1)
result = df.loc[conditions]
display(result) #데이터 프레임 나타낼 때 좀 더 이쁘게 나옴
len(result)

,customer_id,FN,Active,club_member_status,fashion_news_frequency,age
4,00006413d8573cd20ed7128e53b7b13819fe5cfc2d801f...,1,1,ACTIVE,Regularly,52
6,00007d2de826758b65a93dd24ce629ed66842531df6699...,1,1,ACTIVE,Regularly,32
12,00009d946eec3ea54add5ba56d5210ea898def4b46c685...,1,1,ACTIVE,Regularly,56
13,0000ae1bbb25e04bdc7e35f718e852adfb3fbb72ef38b3...,1,1,ACTIVE,Regularly,29
14,0000b2f1829e23b24feec422ef13df3ccedaedc85368e6...,1,1,ACTIVE,Regularly,54
...,...,...,...,...,...,...
1048568,c88f46be101e5795b5d346e861a6b9091b03d8fbb200d6...,1,1,ACTIVE,Regularly,18
1048569,c88f47ef5f8ad8addaafcacff4c1b637efb2e6b81d4d74...,1,1,ACTIVE,Regularly,20
1048570,c88f5971612e659a4e90d6f08d9c29bdf1e4268fcf52d5...,1,1,ACTIVE,Regularly,22
1048571,c88f5d0deba322a686e7928da6a7f3d2318e102d1c2cdb...,1,1,ACTIVE,Regularly,41
1048573,c88fa15c06519c4bdcab386fea313b226113584b729874...,1,1,ACTIVE,Regularly,54

368317

### 문제 3 — 다중 조건
- 나이가 18세 미만 또는 65세 이상인 고객만 필터링하세요.

In [12]:
# TODO: 여기에서 코드를 작성하세요.
mask = (df['age'] < 18) | (df['age'] >= 65)
result = df.loc[mask]
display(result)

,customer_id,FN,Active,club_member_status,fashion_news_frequency,age
15,0000b7a134c3ec0d8842fad1fd4ca28517424c14fc4848...,0,0,ACTIVE,NONE,75
30,00018385675844f7a6babbed41b5655b5727fb16483b6e...,1,1,ACTIVE,Regularly,68
48,000270f6018e827d6d678efe815565a22668fb801b2b89...,1,1,ACTIVE,Regularly,17
81,0003e56a4332b2503e34640be92031ad48f1280ee6e3a7...,1,1,ACTIVE,Regularly,70
102,00048f2f68760664d2d0fa1e7fbfe083f05287f342484c...,0,0,ACTIVE,NONE,67
...,...,...,...,...,...,...
1048455,c88aa754b20ddf462cdae830d5a656640b214c4b90e290...,0,0,ACTIVE,NONE,72
1048456,c88ac888ffccbbf5650626444ac9007cccac3b85870aa5...,1,1,ACTIVE,Regularly,65
1048468,c88b1fe7987c9dad7cc45ac16a6efe3c2a9a52147a3214...,0,0,ACTIVE,NONE,17
1048497,c88c545c87d71f8d1b9c4bfea81115e3adc238f0f505f1...,1,1,ACTIVE,Regularly,72
1048527,c88d8cf96711de782f2b210f44388bb7950a0fb136d998...,0,0,ACTIVE,NONE,69

In [16]:
age_19_65 = df.loc[df['age'].between(19,65)]
display(age_19_65)

,customer_id,FN,Active,club_member_status,fashion_news_frequency,age
0,00000dbacae5abe5e23885899a1fa44253a17956c6d1c3...,0,0,ACTIVE,NONE,49
1,0000423b00ade91418cceaf3b26c6af3dd342b51fd051e...,0,0,ACTIVE,NONE,25
2,000058a12d5b43e67d225668fa1f8d618c13dc232df0ca...,0,0,ACTIVE,NONE,24
3,00005ca1c9ed5f5146b52ac8639a40ca9d57aeff4d1bd2...,0,0,ACTIVE,NONE,54
4,00006413d8573cd20ed7128e53b7b13819fe5cfc2d801f...,1,1,ACTIVE,Regularly,52
...,...,...,...,...,...,...
1048570,c88f5971612e659a4e90d6f08d9c29bdf1e4268fcf52d5...,1,1,ACTIVE,Regularly,22
1048571,c88f5d0deba322a686e7928da6a7f3d2318e102d1c2cdb...,1,1,ACTIVE,Regularly,41
1048572,c88f99a55b10f6dd50dd87c3ca05af4a8a6c98f3e6fbc5...,0,0,ACTIVE,NONE,38
1048573,c88fa15c06519c4bdcab386fea313b226113584b729874...,1,1,ACTIVE,Regularly,54
1048574,c88fa6553539a079a4d49f5b6d286d33bdc7117d0acbb9...,0,0,ACTIVE,NONE,49

### 문제 4 — 다중 조건(특정 값들)
- `fashion_news_frequency`가 'Monthly' 이거나 'Regularly'인 고객만 필터링하세요.

In [19]:
# TODO: 여기에서 코드를 작성하세요.
mask = df['fashion_news_frequency'].isin(['Monthly','Regularly'])
df.loc[mask]

,customer_id,FN,Active,club_member_status,fashion_news_frequency,age
4,00006413d8573cd20ed7128e53b7b13819fe5cfc2d801f...,1,1,ACTIVE,Regularly,52
6,00007d2de826758b65a93dd24ce629ed66842531df6699...,1,1,ACTIVE,Regularly,32
12,00009d946eec3ea54add5ba56d5210ea898def4b46c685...,1,1,ACTIVE,Regularly,56
13,0000ae1bbb25e04bdc7e35f718e852adfb3fbb72ef38b3...,1,1,ACTIVE,Regularly,29
14,0000b2f1829e23b24feec422ef13df3ccedaedc85368e6...,1,1,ACTIVE,Regularly,54
...,...,...,...,...,...,...
1048568,c88f46be101e5795b5d346e861a6b9091b03d8fbb200d6...,1,1,ACTIVE,Regularly,18
1048569,c88f47ef5f8ad8addaafcacff4c1b637efb2e6b81d4d74...,1,1,ACTIVE,Regularly,20
1048570,c88f5971612e659a4e90d6f08d9c29bdf1e4268fcf52d5...,1,1,ACTIVE,Regularly,22
1048571,c88f5d0deba322a686e7928da6a7f3d2318e102d1c2cdb...,1,1,ACTIVE,Regularly,41
1048573,c88fa15c06519c4bdcab386fea313b226113584b729874...,1,1,ACTIVE,Regularly,54

### 문제 5 — 결측치 조건
- `fashion_news_frequency`가 결측(`NaN`)인 고객만 필터링하세요.

In [23]:
# TODO: 여기에서 코드를 작성하세요.
df['fashion_news_frequency'].isna().sum()
mask = df['fashion_news_frequency'].isna()
result = df.loc[mask]
display(result)
print(df['fashion_news_frequency'].value_counts())

,customer_id,FN,Active,club_member_status,fashion_news_frequency,age
876108,a79d9cbfaceb0d25a91caccfad167d4d6391fd5bb4292b...,1,0,ACTIVE,NaN,38

fashion_news_frequency
NONE         674698
Regularly    373218
Monthly         658
Name: count, dtype: int64

### 문제 6 — 정렬
- 나이(`age`) 기준 **내림차순**으로 정렬하여 상위 5명을 출력하세요.

In [25]:
# TODO: 여기에서 코드를 작성하세요.
mask = df.sort_values(by='age', ascending = False)
display(mask.head())

,customer_id,FN,Active,club_member_status,fashion_news_frequency,age
847058,a2106ba216f519880fbebd7a1fe1929802ac1258adabbf...,1,1,ACTIVE,Regularly,99
311081,3b9ec1854ba779c3c11389985299e642b5779947ff8395...,1,1,ACTIVE,Regularly,99
308676,3b28156770e0a17436b29831e41394528f74b4ec2c37d3...,0,0,ACTIVE,NONE,99
546159,687c675e64e5f5d962c99ebf915da230be8c907a65a1d5...,0,0,PRE-CREATE,NONE,99
836730,a01bd2e0e8bbf8db61f0e623a05325cde84955a37415b7...,1,1,ACTIVE,Regularly,99

### 문제 7 — 다중 정렬
- `Active` **내림차순**, `age` **오름차순** 순서로 다중 정렬하세요.

In [26]:
# TODO: 여기에서 코드를 작성하세요.
df.sort_values(by=['Active', 'age'], ascending = [False, True])

,customer_id,FN,Active,club_member_status,fashion_news_frequency,age
1539,0049c08ee3fbe0bee305a3b30153e76f38a0640044db16...,1,1,ACTIVE,Regularly,16
19066,03ad8309930e4978125c3e1a00f7d6b975995b64aa5d17...,1,1,PRE-CREATE,Regularly,16
35880,06e49a51cb667123ab815bef64d4ac94ac5ed7299b3b10...,1,1,ACTIVE,Regularly,16
41552,07fa3e88cfda69773153e19dd1bc46fb3391c9df2883b2...,1,1,ACTIVE,Regularly,16
51361,09d5e6bb83786d81e5cd0c7c32827e3b04b680e973daac...,1,1,ACTIVE,Regularly,16
...,...,...,...,...,...,...
286274,36d219eb822d04d07e5bb31e39caffefc17da81ff4a19b...,0,0,ACTIVE,NONE,99
308676,3b28156770e0a17436b29831e41394528f74b4ec2c37d3...,0,0,ACTIVE,NONE,99
546159,687c675e64e5f5d962c99ebf915da230be8c907a65a1d5...,0,0,PRE-CREATE,NONE,99
613464,7558adbc0401acdd74a7c8633ad97d25979e9859b8abca...,0,0,ACTIVE,NONE,99
839909,a0b9e2473f699821b72833824a3e95972862039a49c5e9...,0,0,PRE-CREATE,NONE,99

### 문제 8 — 열 제거
- 분석에 불필요하다고 가정하고 `FN` 열을 **제거**한 새로운 DataFrame을 만들어 컬럼 목록을 출력하세요.

In [34]:
# TODO: 여기에서 코드를 작성하세요.
del_df = df.drop(columns='FN')
del_df.columns.tolist()

['customer_id',
 'Active',
 'club_member_status',
 'fashion_news_frequency',
 'age']

### 문제 9 — 열 이름 변경
- `age`를 `나이`, `Active`를 `활성`으로 **열 이름 변경**한 DataFrame을 만들어 컬럼 목록을 출력하세요.

In [37]:
# TODO: 여기에서 코드를 작성하세요.
result = df.rename(columns={'age':'나이', 'Active':'활성'})
result.columns.tolist()

['customer_id',
 'FN',
 '활성',
 'club_member_status',
 'fashion_news_frequency',
 '나이']

### 문제 10 — 결측치 개수
- 각 열의 결측치 개수를 한 번에 확인하세요.

In [32]:
# TODO: 여기에서 코드를 작성하세요.
df.isna().sum(axis=0)

customer_id               0
FN                        0
Active                    0
club_member_status        0
fashion_news_frequency    1
age                       0
dtype: int64

### 문제 11 — 결측치 채우기
- 문제 10번에서 확인한 결측치를 합당한 이유에 맞게 삭제 or 대체해보세요!

In [42]:
# TODO: 여기에서 코드를 작성하세요.
mask = df['fashion_news_frequency'].isna()
result = df.loc[mask].dropna
display(result)

<bound method DataFrame.dropna of                                               customer_id  FN  Active  \
876108  a79d9cbfaceb0d25a91caccfad167d4d6391fd5bb4292b...   1       0

       club_member_status fashion_news_frequency  age
876108             ACTIVE                    NaN   38  >

In [49]:
mask = df['age'].between(30,39)
df.loc[mask,'fashion_news_frequency'].value_counts()

fashion_news_frequency
NONE         122508
Regularly     58442
Monthly         161
Name: count, dtype: int64

### 문제 12 — 중복 확인 및 제거
- 중복 행 개수를 확인하고, 중복을 제거한 DataFrame을 만든 뒤 제거 전/후 행 개수를 비교하세요.

In [44]:
# TODO: 여기에서 코드를 작성하세요.
df.duplicated().sum()

np.int64(0)